### ISSUE TITLE
Typo in requirements.txt; dependency error 

### ISSUE THREAD

**Issue by kronkinatorix** [davidmartinrius/speech-dataset-generator#2]
chromadb=0.4.23 should be chromadb=0.4.23. 

Excited to see how this bad boy works. I recently put together something similar but pretty basic in bash to do as much of the manual mucky muck of dataset assembly as possible for me. Yours sounds quite a bit more involved than mine though 

oh: 
ERROR: Cannot install -r requirements.txt (line 10) and gradio because these package versions have conflicting dependencies.
changing yt-dlp==2023.12.30 to yt-dlp seems to have righted the ship.

**Comment by kronkinatorix** [comment]
Oh - running it now and what's being produced after running deepfiltrnet3 is very garbled. Don't think it's working correctly :(

**Comment by davidmartinrius** [comment]
> chromadb=0.4.23 should be chromadb=0.4.23.
> 
> Excited to see how this bad boy works. I recently put together something similar but pretty basic in bash to do as much of the manual mucky muck of dataset assembly as possible for me. Yours sounds quite a bit more involved than mine though
> 
> oh: ERROR: Cannot install -r requirements.txt (line 10) and gradio because these package versions have conflicting dependencies. changing yt-dlp==2023.12.30 to yt-dlp seems to have righted the ship.

Thank you! I fixed it in requirements.txt

**Comment by davidmartinrius** [comment]
> Oh - running it now and what's being produced after running deepfiltrnet3 is very garbled. Don't think it's working correctly :(

Please, could you share the command that you are using and the audio/audios you are trying to process?

**Comment by kronkinatorix** [comment]
So I tried running it outside of your script and the speech was the same - sounds like someone's fast forwarding a cassette in between people talking on a more careful listen - which as I understand it should affect the dataset once everything is cut and tucked away all ticky boo, so I think this is working correctly. 

Here's 2 min from the enhanced folder regardless - it's from an episode of star trek the next generation :) https://drive.google.com/file/d/1GaC09aqKPEMh3lnYnboWLdYTphjinJFj/view?usp=drive_link

I ran into a wrinkle after the enhance stage, however - the script was exiting early before it processed the audio. 

same error with:  python3 main.py --input_folder /home/....--output_directory........--range_times 0-45 

python3 main.py --input_folder.....--output_directory...... --types deepfilternet enhance_audio_resembleai _mayavoz (happens without this too, saw it wasn't implemented after the fact). 

with the above being said, I did run into another wrinkle.  The script exits when running inaspeechsegmenter. 

I dug around a bit and made sure tensorflow was installed due to a tensorflow error that poos up and it didn't fix anything but It was caused by inaspeechsegmenter calling the get_file function from keras - which itself relied on importing "c" which I couldn't install because it called for the installation of a version of pandas that depended on python==3.6. 

Without the tensorflow error popping up the script exits with a 0 after this in an strace:

newfstatat(AT_FDCWD, "/home............//chroma_database/chroma.sqlite3", {st_mode=S_IFREG|0644, st_size=147456, ...}, 0) = 0
close(9)       

 though I think may be related to triton given the keras error and because this happens right before the exist: 

rename("/home/......triton/autotune/Fp16Matmul_4d_kernel.pickle.tmp", "/home/......./.triton/autotune/Fp16Matmul_4d_kernel.pickle") = 0

Maybe your script or inaspeech is calling the triton model by the wrong name? Just a thought.

**Comment by kronkinatorix** [comment]
Oh - I spoke to soon. 

Looks like the output directory needs to not be nested anywhere in the input directory. I guess there's some recursion happening. No error when setting the output dir to outside of the input dir.

**Comment by davidmartinrius** [comment]
## Part 1

I think enhance_audio_resembleai is what is causing the weird sounds, have you tried with only deepfilternet?

Actually --types can be combined, but there is no need to combine them. So... you can try just passing deepfilternet and see if the output is good enough.

enhance_audio_resembleai can be tricky. These are the main parameters:

solver = "midpoint" #rk4, euler, midpoint
denoising = True
nfe = 128 #range from 1 to 128
tau = 0 #range from 0 to 1

You can use deepfilternet alone, you can use resemleai alone as well. 
Or also you can play with these parameters. If you are using deepfilternet before resembleai you can set denoising to False, nfe can be reduced, you could try 64 for example.
tau is too sensitive and only a tau of 0.2 can worsen even more the audio quality.

There are other solvers as well: rk4, euler and midpoint.

You can play with this combinations. It is not officially documented yet in this project.

## Part 2

I will review the dependencies error. Yesterday, I updated the requirements.txt Today I created a new environment, installed everything from scratch and no problems when executing the code. Have you tried creating an enviornment from scratch? Please update the code before installing again.

## Part 3

About nesting output and input, I have not tried it. I always use separate directories, but I could make it work when nesting as well.

**Comment by kronkinatorix** [comment]
Just came back to take another crack at this and got an error on the mayavoz install from the requirements.txt.
Delete the mayavoz line and replaced it with the (same? weird) line and it worked; - maybe an error from the cache on an earlier install. 
changing it to git+https://github.com/davidmartinrius/mayavoz.git%  

am gettin an import error on speech_dataset_generation though. moving main.py and __init__.py to the main speech-dataset-gemeratpr dir seems to have fixed it though. 

I'm giving it a go at my raw audio with deepfilternet only. I'll let you know how it goes.

**Comment by davidmartinrius** [comment]
Hi @kronkinatorix , I just made a clean installation and it worked well. Probably it happened because of the cache.

**Comment by kronkinatorix** [comment]
Going to give this a shot with a fresh venv - erroring out in the current one with: 2024-02-29 17:22:41.785692: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8902
2024-02-29 17:22:41.812193: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
Traceback (most recent call last):
  File "/home/mb/gitclones/speech-dataset-generator/main.py", line 46, in <module>
    process_audio_files(audio_files, output_directory, start, end, enhancers, datasets)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/audio_processor/audio_processor.py", line 51, in process_audio_files
    dataset_generator.process(audio_file, output_directory, start, end, enhancers, collection, datasets)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/dataset_generator/dataset_generator.py", line 371, in process
    enhanced_audio_file_path = self.audio_manager_instance.process(path_to_audio_file, output_directory, enhancers)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/audio_manager/audio_manager.py", line 33, in process
    if not self.has_speech_quality(output_audio_file):
  File "/home/.......speech-dataset-generator/speech_dataset_generator/audio_manager/audio_manager.py", line 193, in has_speech_quality
    scores = self.metrics(path_to_audio_file)
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/__init__.py", line 117, in __call__
    result_metric = metric.test(*files, array_rate=rate)
  File "/hom......speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/__init__.py", line 88, in test
    result_t = self.test_window([audio[win] for audio in audios],
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/absolute/srmr/__init__.py", line 14, in test_window
    return {'srmr': srmr(audios[0], self.fixed_rate, n_cochlear_filters=23,
  File "/home.....speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/absolute/srmr/srmr.py", line 92, in srmr
    K90perc_idx = np.where(AC_perc_cumsum > 90)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by davidmartinrius** [comment]
Ok, better clone a new repo again

**Comment by kronkinatorix** [comment]
SO the mayavoz install error crops up on pip install -e . and not on pip install

Still can't run speech_dataset_generator main.py - wouldn't that need to be in the main folder though for python to pull all the imports?

**Comment by kronkinatorix** [comment]
can't launch :(
Script at least starts if I move main

 I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
Loaded  speechmetrics.absolute.mosnet
Loaded  speechmetrics.absolute.srmr
2024-02-29 18:15:05 | INFO     | DF | Running on torch 2.1.1+cu121
2024-02-29 18:15:05 | INFO     | DF | Running on host mmint
2024-02-29 18:15:05 | INFO     | DF | Git commit: 60ad653, branch: main
2024-02-29 18:15:05 | INFO     | DF | Loading model settings of DeepFilterNet3
2024-02-29 18:15:05 | INFO     | DF | Using DeepFilterNet3 model at /home/mb/.cache/DeepFilterNet/DeepFilterNet3
2024-02-29 18:15:05 | INFO     | DF | Initializing model `deepfilternet3`
2024-02-29 18:15:05 | INFO     | DF | Found checkpoint /home/mb/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2024-02-29 18:15:05 | INFO     | DF | Running on device cuda:0
2024-02-29 18:15:05 | INFO     | DF | Model loaded
2024-02-29 18:17:44.941529: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8902
2024-02-29 18:17:44.966941: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
Traceback (most recent call last):
  File "/home/mb/gitclones/speech-dataset-generator/main.py", line 46, in <module>
    process_audio_files(audio_files, output_directory, start, end, enhancers, datasets)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/audio_processor/audio_processor.py", line 54, in process_audio_files
    dataset_generator.process(audio_file, output_directory, start, end, enhancers, collection, datasets)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/dataset_generator/dataset_generator.py", line 371, in process
    enhanced_audio_file_path = self.audio_manager_instance.process(path_to_audio_file, output_directory, enhancers)
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/audio_manager/audio_manager.py", line 33, in process
    if not self.has_speech_quality(output_audio_file):
  File "/home/mb/gitclones/speech-dataset-generator/speech_dataset_generator/audio_manager/audio_manager.py", line 193, in has_speech_quality
    scores = self.metrics(path_to_audio_file)
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/__init__.py", line 117, in __call__
    result_metric = metric.test(*files, array_rate=rate)
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/__init__.py", line 88, in test
    result_t = self.test_window([audio[win] for audio in audios],
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/absolute/srmr/__init__.py", line 14, in test_window
    return {'srmr': srmr(audios[0], self.fixed_rate, n_cochlear_filters=23,
  File "/home/mb/gitclones/speech-dataset-generator/venv/lib/python3.10/site-packages/speechmetrics/absolute/srmr/srmr.py", line 92, in srmr
    K90perc_idx = np.where(AC_perc_cumsum > 90)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
(venv) ┌────(mb㉿mmint)-[~/gitclones/speech-dataset-generator]
└─$                                                                         1 ⨯

**Comment by davidmartinrius** [comment]
Got it, I pushed a bugfix in setup.py :+1: 

Before telling you this I cloned and installed the repo from scratch again to ensure it works well when installing from pip install -e .

**Comment by davidmartinrius** [comment]
after cloning and installing do you execute something like this?

python speech_dataset_generator/main.py --input_file_path /path/to/your/audio.mp3 --output_directory ./output_folder --range_times 4-10

**Comment by davidmartinrius** [comment]
The requirements.txt is working. If you have another issue you can open a new ticket. Thank you.
